# Generated by Django 3.2.6 on 2022-01-27 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Username', models.CharField(max_length=50)),
                ('Number', models.IntegerField(null=True)),
                ('Profile_pic', models.ImageField(null=True, upload_to='img')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Address', models.TextField(null=True)),
                ('Reviews', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User_id')),
            ],
        ),
    ]
