# Generated by Django 3.2.6 on 2022-01-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_architectureaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectureaccount',
            name='city',
            field=models.CharField(default='Nadiad', max_length=50, verbose_name='Location_City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='architectureaccount',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Created_at'),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='city',
            field=models.CharField(default='Nadiad', max_length=50, verbose_name='Location_City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Created_at'),
        ),
    ]
