# Generated by Django 4.0.3 on 2022-04-16 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220127_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='img/projects')),
                ('posted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.clientaccount')),
            ],
        ),
    ]
