# Generated by Django 4.0.3 on 2022-04-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='apply_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.architectureaccount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(null=True, upload_to='img/projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientaccount'),
        ),
    ]
